Description: Signing Certificate Management for Brighid Identity.
Transform: AWS::Serverless-2016-10-31
Parameters:
  LambdajectionLayerVersion:
    Type: String
    Description: ARN of the Lambda Layer containing Lambdajection + its dependencies

  DotnetLayerVersion:
    Type: String
    Description: ARN of the Lambda Layer containing .NET

  CertificateConfigurationParameter:
    Type: String
    Description: Name of the parameter where certificate configuration lives.

  RotationInterval:
    Type: String
    Description: Rate at which certificates are rotated.

Resources:
  CertificateBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  CertificateRotator:
    Type: AWS::Serverless::Function
    Properties:
      Handler: CertificateRotator::Brighid.Identity.Certificates.CertificateRotator.Handler::Run
      Runtime: provided.al2
      Timeout: 30
      CodeUri: ../bin/CertificateRotator/Release/net5.0/linux-x64/publish/
      MemorySize: 512
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:dotnet:${DotnetLayerVersion}
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:lambdajection:${LambdajectionLayerVersion}
      Policies:
        - AWSLambdaExecute
        - !Ref CertificateRotatorPolicy
      Events:
        Interval:
          Type: Schedule
          Properties:
            Schedule: !Sub rate(${RotationInterval})
            Input: "{}"
      Environment:
        Variables:
          Certificate__BucketName: !Ref CertificateBucket
          Certificate__ConfigurationParameterName: !Ref CertificateConfigurationParameter

  CertificateRotatorPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:PutParameter
            Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${CertificateConfigurationParameter}

          - Effect: Allow
            Action: s3:*Object
            Resource: !Sub ${CertificateBucket.Arn}/*

  CertificateReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: ssm:GetParameter
            Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${CertificateConfigurationParameter}

          - Effect: Allow
            Action: s3:GetObject
            Resource: !Sub ${CertificateBucket.Arn}/*

Outputs:
  CertificateBucketArn:
    Value: !GetAtt CertificateBucket.Arn
    Description: ARN of the bucket where certificates live.
    Export:
      Name: !Sub ${AWS::StackName}:CertificateBucketArn

  CertificateReadPolicyArn:
    Value: !Ref CertificateReadPolicy
    Description: ARN of the policy granting read access to certificates and certificate configuration.
    Export:
      Name: !Sub ${AWS::StackName}:CertificateReadPolicyArn
