Description: Signing Certificate Management for Brighid Identity.
Transform: AWS::Serverless-2016-10-31
Parameters:
  LambdajectionLayerVersion:
    Type: String
    Description: ARN of the Lambda Layer containing Lambdajection + its dependencies

  DotnetLayerVersion:
    Type: String
    Description: ARN of the Lambda Layer containing .NET

Resources:
  CertificateBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  CertificateRotator:
    Type: AWS::Serverless::Function
    Properties:
      Handler: CertificateRotator::Brighid.Identity.Certificates.CertificateRotator.Handler::Run
      Runtime: provided.al2
      Timeout: 30
      CodeUri: ../bin/CertificateRotator/Release/net5.0/linux-x64/publish/
      MemorySize: 512
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:dotnet:${DotnetLayerVersion}
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:lambdajection:${LambdajectionLayerVersion}
      Policies:
        - AWSLambdaExecute
        - !Ref CertificateRotatorPolicy
      Environment:
        Variables:
          Certificate__BucketName: !Ref CertificateBucket

  CertificateRotatorPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: s3:ListBucket
            Resource: !GetAtt CertificateBucket.Arn

          - Effect: Allow
            Action: s3:*Object
            Resource: !Sub ${CertificateBucket.Arn}/*

Outputs:
  CertificateBucketArn:
    Value: !GetAtt CertificateBucket.Arn
    Description: ARN of the bucket where certificates live.
    Export:
      Name: !Sub ${AWS::StackName}:CertificateBucketArn
